defaults: &defaults
  :app_name: "Cover Story"
  :tmp_dir: "/tmp"
  :analyzer_filetype_path: "lib/log_parser/request_log_analyzer/rails_pa.rb"
  :applications: 'hr_suite, applicant_portal, employee_portal'
  :log_config:
    :log_file_format: '(?<ci_job_num>[\d]*)-*(?<ci_job>[\w\ ]*)-*(?<env>development|production|test).log'
    :environments: 'production, test, development'
    :routes_file_matcher: 'routes'
    :log_file_matcher: 'log'
    :meta_file_matcher: 'meta'
  :routes_config:
    :type: "rails"
    :routes_path_prefix: "/hr"
    :routes_path_prefix_file_matcher: "hr_suite"
  :analysis_config:
    :import_defaults: "log"
    :tested_title: "Tested Routes"
    :tested_x_axis_label: "Test Run"
    :tested_y_axis_label: "Coverage Percentage"

development:
  <<: *defaults
  :file_drop_dir: "tmp/file_import/"
  :splunk_config:
    :host: localhost
    :port: 8089
    :user: admin
    :pass: w3testpeople
    :app: rails_splunk

test:
  <<: *defaults
  :file_drop_dir: "tmp/file_import/"
  :splunk_config:
    :host: localhost
    :port: 8089
    :user: admin
    :pass: w3testpeople
    :app: rails_splunk

production:
  <<: *defaults
  :file_drop_dir:
  :splunk_config:
    :host: localhost
    :port: 8089
    :user: admin
    :pass: w3testpeople
    :app: rails_splunk
