defaults: &defaults
  :app_name: "Cover Story"
  :tmp_dir: "/tmp"
  :analyzer_filetype_path: "lib/log_parser/request_log_analyzer/rails_pa.rb"

development:
  <<: *defaults
  :log_drop_dir: "tmp/routes_import/"
  :splunk_config:
    :host: localhost
    :port: 8089
    :user: admin
    :pass: w3testpeople
    :app: rails_splunk
  :routes_config:
    :import_file_path: "tmp/routes_import/hrsuite_routes.txt"

test:
  <<: *defaults
  :log_drop_dir: "tmp/routes_import/"
  :splunk_config:
    :host: localhost
    :port: 8089
    :user: admin
    :pass: w3testpeople
    :app: rails_splunk
  :routes_config:
    :import_file_path: "tmp/routes_import/hrsuite_routes.txt"

production:
  <<: *defaults
  :splunk_config:
    :host: localhost
    :port: 8089
    :user: admin
    :pass: w3testpeople
    :app: rails_splunk
