development:
  adapter: mysql2
  encoding: utf8
  database: coverstory_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: coverstory_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: coverstory_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  host: 127.0.0.1
  port: 3306
